# Generated by Django 4.2.2 on 2023-07-01 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount')),
                ('date', models.DateField(verbose_name='Date to reach goal')),
                ('monthly_deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly deposite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saving Goal',
                'verbose_name_plural': 'Saving Goals',
                'ordering': ('-created_at',),
            },
        ),
    ]
